version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: eventify-postgres
    environment:
      POSTGRES_DB: eventify_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d eventify_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 