spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  application:
    name: eventify

  datasource:
    url: jdbc:postgresql://localhost:5432/eventify_db?currentSchema=eventify
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    default-schema: eventify

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        web: TRACE
        security: DEBUG
      springdoc: DEBUG
    root: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true


jwt:
  secret: gmrsShfWlzTW71NK9C2dpKqahbLN+JwGLH/FUl+rUqHYHnSlzOX45jCI/KQy5L4qd0Yu9wDDHo4BR2qOQzv8+Sj28s1TfrTZh/DlmCJdHwhA5lKDeJnkSsSkmq/UBpfdYV9hRKSyvTXsKEHBZwOBoaw1KSeSvwAOBFWQWNzQb0fcbrTDRaqT2bsZX8j1jLSXqUPHnoyisHGa1LkiRCXc8VSRHk2CgkaVc4nhmpRpcH66lGwtpNhbDdaqo4h+nua+MdnxcSA1lY0DUivMH1sw1aX9a2EDUD8rvhaepPI9V4d8fjUfNwc+1Fxtm934F+e7+dWtqPSB8BtHvCNZ0BcHZY4990GeYNB3ufA0rRJCaGo=
  expiration: 360000
