spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  application:
    name: eventify

  datasource:
    url: jdbc:postgresql://localhost:5432/eventify_db?currentSchema=eventify
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    default-schema: eventify

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        web: TRACE
        security: DEBUG
      springdoc: DEBUG
    root: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true


jwt:
  secret: your256bitsecretLineAndMethodictsakKKALonglongLongLongLongbitsecRetKeyItsEnoughLargeForYouOrNotIdontKnowButIhopeItCanBeEnoughForBlaBlaBlaBlaThungThungThungSahurBombardirocrocodilloyour256bitsecretLineAndMethodictsakKKALonglongLongLongLongbitsecRetKeyItsEnoughLargeForYouOrNotIdontKnowButIhopeItCanBeEnoughForBlaBlaBlaBlaThungThungThungSahurBombardirocrocodillo
  expiration: 360000
